name: Run Books API Tests

on:
  push:
    branches: [ main, apiautomation ]
  pull_request:
    branches: [ main, apiautomation ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven and run tests
        run:  mvn test -Dtest=TestRunner
